In [1]:
import numpy as np
## torch neural network library
import torch.nn as nn
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)


tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
tensor([[-1.5401, -0.4425, -0.4684],
        [-0.8724, -0.7931,  0.3274]], requires_grad=True)
tensor([-0.7888,  0.1240], requires_grad=True)


In [2]:
from torch.utils.data import TensorDataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [3]:
from torch.utils.data import DataLoader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)


In [4]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 91.,  88.,  64.],
        [ 73.,  67.,  43.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 81., 101.],
        [ 56.,  70.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [6]:
import torch.nn as nn
## torch function for randomizing weights and biases
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.4922,  0.3907,  0.1882],
        [-0.2683,  0.0679,  0.2562]], requires_grad=True)
Parameter containing:
tensor([ 0.1069, -0.2399], requires_grad=True)


In [7]:
list(model.parameters())
preds = model(inputs)
preds


tensor([[ -1.5524,  -4.2582],
        [  1.7456,  -2.2808],
        [ 20.5595,   0.3768],
        [-26.3336, -15.2043],
        [ 16.8294,   5.7015]], grad_fn=<AddmmBackward>)

In [8]:
import torch.nn.functional as F

## loss function
loss_fn = F.mse_loss
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(7837.7515, grad_fn=<MseLossBackward>)


In [15]:
## optimizer function
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

## training the model for 100- epochs
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
   
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradient
            loss.backward()
            
            # 4. update values using optimizer function
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Progress of training
        if (epoch+1) % 20 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [16]:
# running the model
fit(1000, model, loss_fn, opt, train_dl)


Epoch [20/1000], Loss: 0.6810
Epoch [40/1000], Loss: 0.6748
Epoch [60/1000], Loss: 0.6688
Epoch [80/1000], Loss: 0.6630
Epoch [100/1000], Loss: 0.6575
Epoch [120/1000], Loss: 0.6521
Epoch [140/1000], Loss: 0.6470
Epoch [160/1000], Loss: 0.6420
Epoch [180/1000], Loss: 0.6373
Epoch [200/1000], Loss: 0.6327
Epoch [220/1000], Loss: 0.6282
Epoch [240/1000], Loss: 0.6239
Epoch [260/1000], Loss: 0.6198
Epoch [280/1000], Loss: 0.6159
Epoch [300/1000], Loss: 0.6120
Epoch [320/1000], Loss: 0.6084
Epoch [340/1000], Loss: 0.6048
Epoch [360/1000], Loss: 0.6014
Epoch [380/1000], Loss: 0.5981
Epoch [400/1000], Loss: 0.5950
Epoch [420/1000], Loss: 0.5919
Epoch [440/1000], Loss: 0.5890
Epoch [460/1000], Loss: 0.5861
Epoch [480/1000], Loss: 0.5834
Epoch [500/1000], Loss: 0.5808
Epoch [520/1000], Loss: 0.5782
Epoch [540/1000], Loss: 0.5758
Epoch [560/1000], Loss: 0.5735
Epoch [580/1000], Loss: 0.5712
Epoch [600/1000], Loss: 0.5690
Epoch [620/1000], Loss: 0.5669
Epoch [640/1000], Loss: 0.5649
Epoch [660/1

In [17]:
preds = model(inputs)
preds

tensor([[ 57.1956,  70.2848],
        [ 82.0940, 100.5660],
        [118.9012, 133.2337],
        [ 21.1383,  37.0956],
        [101.7125, 118.8631]], grad_fn=<AddmmBackward>)

In [18]:
# compare predictions with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [19]:
# new prediction using the trained model
model(torch.tensor([[75, 63, 44.]]))


tensor([[53.6597, 67.3825]], grad_fn=<AddmmBackward>)